import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'es' | 'en' | 'zh';

const translations = {
  es: {
    // General / Header
    "app.title": "Compartir",
    "app.subtitle": "Transporte Inteligente",
    "app.explore": "Explorar",
    "app.admin": "Admin",
    "app.logout": "Cerrar Sesión",
    "app.loading": "Cargando Sistema...",
    "app.loadingSub": "Verificando sesión segura",
    "app.userRole": "Usuario",
    "app.adminRole": "Administrador",
    "app.userLogout": "Cerrar Sesión de Usuario",
    "app.adminLogout": "Cerrar Sesión Administrativa",
    "app.cancel": "Cancelar",

    // Login screen
    "login.subtitle": "Tu guía de transporte en Nicaragua",
    "login.googleBtn": "Iniciar Sesión con Google",
    "login.signingIn": "Iniciando sesión...",
    "login.orForm": "O ingresa tus datos",
    "login.userPlaceholder": "Nombre",
    "login.usernamePlaceholder": "Nombre",
    "login.passwordPlaceholder": "Contraseña",
    "login.localBtn": "Iniciar Sesión",
    "login.errorCredits": "Credenciales incorrectas. Favor intente de nuevo.",
    "login.errorGoogle": "Error al iniciar sesión con Google: ",
    "login.credentialsTitle": "Acceso con Credenciales / Teléfono",
    "login.credentialsPlaceholder": "Nombre o número de teléfono registrado",
    "login.noAccount": "¿No tienes una cuenta? ",
    "login.createOne": "Crear una",
    "login.createAccountTitle": "Crear nueva cuenta",
    "login.fullNamePlaceholder": "Nombre completo (Obligatorio)",
    "login.phonePlaceholder": "Número de teléfono (Obligatorio - Identificador único)",
    "login.emailPlaceholder": "Correo electrónico (Opcional - sin validar)",
    "login.registerBtn": "Registrarse y Entrar",
    "login.alreadyHaveAccount": "¿Ya tienes una cuenta? ",
    "login.signInBtn": "Iniciar Sesión",
    "login.loggingIn": "Ingresando...",
    "login.creating": "Creando...",
    "login.errorNotFound": "Credenciales incorrectas o usuario no encontrado.",
    "login.errorNotRegistered": "Este número de teléfono no está registrado. Toca abajo en \"Crear una\" para registrarte.",
    "login.errorRequired": "El Nombre y Número de teléfono son obligatorios.",
    "login.errorAlreadyRegistered": "Este número de teléfono ya está registrado. Intenta iniciar sesión con él.",
    "login.errorRegister": "Error al registrarte: ",

    // Route Search
    "search.routesBtn": "Buscar Rutas",
    "search.favsBtn": "Favoritos",
    "search.title": "¿A dónde vas hoy?",
    "search.desc": "Encuentra la mejor ruta de transporte en Managua",
    "search.originPlaceholder": "Origen (ej. UCA, Naucalpan...)",
    "search.destPlaceholder": "Destino (ej. Metrosur...)",
    "search.gpsBtn": "Usar mi ubicación GPS",
    "search.gpsLocating": "Localizando...",
    "search.submitBtn": "Goo",
    "search.loadingBtn": "Buscando las mejores opciones...",
    "search.favTitle": "Tus Rutas Favoritas",
    "search.favNone": "No tienes rutas guardadas aún.",
    "search.favDesc": "Haz click en el corazón de cualquier ruta para guardarla.",
    "search.suggested": "Rutas Sugeridas",
    "search.bestChoice": "Mejor opción",
    "search.minutes": "Minutos",
    "search.stops": "bahías",
    "search.startBtn": "Iniciar Viaje",
    "search.reportBtn": "Reportar",
    "search.ready": "¿Listo para viajar?",
    "search.readyDesc": "Ingresa tu destino arriba para descubrir las mejores rutas disponibles en Managua.",

    // Navigation Tab
    "nav.titleReal": "Navegación en tiempo real",
    "nav.titleStatic": "Instrucciones de Viaje",
    "nav.live": "En vivo",
    "nav.static": "Estático",
    "nav.assignedDriver": "Chofer Asignado",
    "nav.staticStepPrefix": "Pasa por",
    "nav.guideCenter": "Guía de Viaje",
    "nav.guideCenterDesc": "Revisa cada parada y transbordo estimado para completar tu recorrido sin inconvenientes.",
    "nav.boardInstructions": "Aborda la unidad en esta parada designada.",
    "nav.transferInstructions": "Realiza el transbordo de ruta.",
    "nav.nextOne": "parada siguiente",
    "nav.arriveInstructions": "Bájate aquí. Has llegado a tu destino.",
    "nav.start": "Inicio",
    "nav.completed": "Completado",
    "nav.end": "Destino",
    "nav.nextUnit": "Unidad más cercana en ruta",
    "nav.arrivePrefix": "Tiempo restante:",
    "nav.arriveSuffix": "min",
    "nav.finish": "Terminar Viaje",
    "nav.howToTravel": "¿Cómo deseas viajar?",
    "nav.travelDesc": "Elige el modo que prefieres para visualizar tu trayecto en el mapa.",
    "nav.realTimeOption": "Navegación en Tiempo Real",
    "nav.realTimeDesc": "Sigue la ubicación simulada por GPS en vivo de la unidad y tiempos dinámicos.",
    "nav.staticOption": "Guía Estática de Ruta",
    "nav.staticDesc": "Visualiza la ruta recomendada con sus paradas oficiales sin simulación móvil.",

    // Report Form
    "report.title": "Reportar Incidente",
    "report.subtitle": "Tu seguridad es nuestra prioridad",
    "report.successTitle": "¡Reporte Enviado!",
    "report.successDesc": "Gracias por ayudarnos. El administrador revisará tu reporte pronto.",
    "report.question": "¿Qué deseas reportar?",
    "report.route": "Ruta",
    "report.driver": "Chofer",
    "report.both": "Ambos",
    "report.reasonLabel": "¿Cuál es el motivo?",
    "report.reason_drunk": "Chofer ebrio",
    "report.reason_reckless": "Conducción temeraria",
    "report.reason_bad_condition": "Unidad en mal estado",
    "report.reason_other": "Otro motivo",
    "report.descLabel": "Descripción del suceso",
    "report.descPlaceholder": "Ingresa detalles adicionales que nos ayuden a entender la situación...",
    "report.submitting": "Enviando...",
    "report.sendBtn": "Enviar Reporte",

    // Admin Panel
    "admin.dashboard": "Panel de Control",
    "admin.routes": "Rutas",
    "admin.stops": "Bahías",
    "admin.drivers": "Choferes",
    "admin.reports": "Reportes",
    "admin.schedules": "Horarios",
    "admin.manageSystem": "Gestión del Sistema",
    "admin.addRoute": "Agregar Ruta",
    "admin.addStop": "Agregar Bahía",
    "admin.addDriver": "Agregar Chofer",
    "admin.addSchedule": "Agregar Horario",
    "admin.routeCode": "Código / Placa",
    "admin.routeName": "Nombre de la Ruta",
    "admin.stopName": "Nombre de la Bahía",
    "admin.stopLat": "Latitud",
    "admin.stopLng": "Longitud",
    "admin.driverName": "Nombre del Chofer",
    "admin.driverBio": "Biografía o Información",
    "admin.driverPhoto": "URL de la Foto",
    "admin.saveBtn": "Guardar",
    "admin.editBtn": "Editar",
    "admin.deleteBtn": "Eliminar",
    "admin.configBtn": "Configuración",
    "admin.recentReports": "Reportes Recientes",
    "admin.pending": "Pendiente",
    "admin.resolved": "Resuelto",
    "admin.allSaved": "Datos actualizados exitosamente",
  },
  en: {
    // General / Header
    "app.title": "Share",
    "app.subtitle": "Smart Transit",
    "app.explore": "Explore",
    "app.admin": "Admin",
    "app.logout": "Log Out",
    "app.loading": "Loading System...",
    "app.loadingSub": "Verifying secure session",
    "app.userRole": "User",
    "app.adminRole": "Administrator",
    "app.userLogout": "User Log Out",
    "app.adminLogout": "Admin Log Out",
    "app.cancel": "Cancel",

    // Login screen
    "login.subtitle": "Your transit guide in Nicaragua",
    "login.googleBtn": "Sign in with Google",
    "login.signingIn": "Signing in...",
    "login.orForm": "Or use credentials",
    "login.userPlaceholder": "Username",
    "login.passwordPlaceholder": "Password",
    "login.localBtn": "Local Login",
    "login.errorCredits": "Incorrect credentials. Please try again.",
    "login.errorGoogle": "Error signing in with Google: ",
    "login.credentialsTitle": "Credentials / Phone Sign-In",
    "login.credentialsPlaceholder": "Username or registered phone number",
    "login.noAccount": "Don't have an account? ",
    "login.createOne": "Create one",
    "login.createAccountTitle": "Create new account",
    "login.fullNamePlaceholder": "Full name (Required)",
    "login.phonePlaceholder": "Phone number (Required - Unique Identifier)",
    "login.emailPlaceholder": "Email address (Optional - unvalidated)",
    "login.registerBtn": "Register and Access",
    "login.alreadyHaveAccount": "Already have an account? ",
    "login.signInBtn": "Sign In",
    "login.loggingIn": "Logging in...",
    "login.creating": "Creating...",
    "login.errorNotFound": "Incorrect credentials or user not found.",
    "login.errorNotRegistered": "This phone number is not registered. Tap \"Create one\" below to register.",
    "login.errorRequired": "Name and Phone Number are required.",
    "login.errorAlreadyRegistered": "This phone number is already registered. Try logging in instead.",
    "login.errorRegister": "Error registering: ",

    // Route Search
    "search.routesBtn": "Find Routes",
    "search.favsBtn": "Favorites",
    "search.title": "Where are you going today?",
    "search.desc": "Find the best way to travel around Managua",
    "search.originPlaceholder": "Origin (e.g., UCA, Naucalpan...)",
    "search.destPlaceholder": "Destination (e.g., Metrosur...)",
    "search.gpsBtn": "Use my GPS location",
    "search.gpsLocating": "Locating...",
    "search.submitBtn": "Goo",
    "search.loadingBtn": "Searching premium pathways...",
    "search.favTitle": "Your Favorite Routes",
    "search.favNone": "You don't have any saved routes yet.",
    "search.favDesc": "Click the heart on any route to save it to your list.",
    "search.suggested": "Suggested Routes",
    "search.bestChoice": "Best option",
    "search.minutes": "Minutes",
    "search.stops": "stops",
    "search.startBtn": "Start Trip",
    "search.reportBtn": "Report",
    "search.ready": "Ready to go?",
    "search.readyDesc": "Enter your destination above to discover the best routes available in Managua.",

    // Navigation Tab
    "nav.titleReal": "Real-time Navigation",
    "nav.titleStatic": "Travel Instructions",
    "nav.live": "Live",
    "nav.static": "Static",
    "nav.assignedDriver": "Assigned Driver",
    "nav.staticStepPrefix": "Passes through",
    "nav.guideCenter": "Travel Guide",
    "nav.guideCenterDesc": "Check each estimated stop and transfer below to complete your route smoothly.",
    "nav.boardInstructions": "Board the transit vehicle at this designated stop.",
    "nav.transferInstructions": "Perform the route transfer.",
    "nav.nextOne": "next stop",
    "nav.arriveInstructions": "Get off here. You have arrived at your destination.",
    "nav.start": "Start",
    "nav.completed": "Completed",
    "nav.end": "Destination",
    "nav.nextUnit": "Nearest unit on route",
    "nav.arrivePrefix": "Remaining time:",
    "nav.arriveSuffix": "min",
    "nav.finish": "End Trip",
    "nav.howToTravel": "How do you want to travel?",
    "nav.travelDesc": "Choose your preferred mode to visualize your journey on the map.",
    "nav.realTimeOption": "Real-time Navigation",
    "nav.realTimeDesc": "Follow the live GPS-simulated location of the transit unit and dynamic times.",
    "nav.staticOption": "Static Route Guide",
    "nav.staticDesc": "View the recommended route with its official stops without mobile simulation.",

    // Report Form
    "report.title": "Report Incident",
    "report.subtitle": "Your safety is our priority",
    "report.successTitle": "Report Sent!",
    "report.successDesc": "Thank you for helping us. An administrator will review your report shortly.",
    "report.question": "What would you like to report?",
    "report.route": "Route",
    "report.driver": "Driver",
    "report.both": "Both",
    "report.reasonLabel": "What is the reason?",
    "report.reason_drunk": "Drunk driver",
    "report.reason_reckless": "Reckless driving",
    "report.reason_bad_condition": "Bus in bad condition",
    "report.reason_other": "Other reason",
    "report.descLabel": "Event details",
    "report.descPlaceholder": "Write additional details to help us understand...",
    "report.submitting": "Submitting...",
    "report.sendBtn": "Send Report",

    // Admin Panel
    "admin.dashboard": "Control Panel",
    "admin.routes": "Routes",
    "admin.stops": "Stops",
    "admin.drivers": "Drivers",
    "admin.reports": "Reports",
    "admin.schedules": "Schedules",
    "admin.manageSystem": "System Management",
    "admin.addRoute": "Add Route",
    "admin.addStop": "Add Stop",
    "admin.addDriver": "Add Driver",
    "admin.addSchedule": "Add Schedule",
    "admin.routeCode": "Code / Plate",
    "admin.routeName": "Route Name",
    "admin.stopName": "Stop Name",
    "admin.stopLat": "Latitude",
    "admin.stopLng": "Longitude",
    "admin.driverName": "Driver Name",
    "admin.driverBio": "Biography or Info",
    "admin.driverPhoto": "Photo URL",
    "admin.saveBtn": "Save",
    "admin.editBtn": "Edit",
    "admin.deleteBtn": "Delete",
    "admin.configBtn": "Settings",
    "admin.recentReports": "Recent Reports",
    "admin.pending": "Pending",
    "admin.resolved": "Resolved",
    "admin.allSaved": "Data customized successfully",
  },
  zh: {
    // General / Header
    "app.title": "分享",
    "app.subtitle": "智能交通指南",
    "app.explore": "探索路线",
    "app.admin": "管理端",
    "app.logout": "退出登录",
    "app.loading": "系统加载中...",
    "app.loadingSub": "正在验证安全会话",
    "app.userRole": "普通用户",
    "app.adminRole": "管理员",
    "app.userLogout": "退出用户登录",
    "app.adminLogout": "退出管理员登录",
    "app.cancel": "取消",

    // Login screen
    "login.subtitle": "您的尼加拉瓜公共交通出行助手",
    "login.googleBtn": "使用 Google 账户登录",
    "login.signingIn": "登录中...",
    "login.orForm": "或使用账号密码登录",
    "login.userPlaceholder": "用户名",
    "login.passwordPlaceholder": "密码",
    "login.localBtn": "本地登录",
    "login.errorCredits": "凭据不正确，请重新输入。",
    "login.errorGoogle": "Google 登录发生错误：",
    "login.credentialsTitle": "使用凭据 / 电话号码登录",
    "login.credentialsPlaceholder": "用户名或已注册的手机号码",
    "login.noAccount": "还没有账号吗？ ",
    "login.createOne": "注册一个",
    "login.createAccountTitle": "创建新账户",
    "login.fullNamePlaceholder": "真实姓名 (必填)",
    "login.phonePlaceholder": "电话号码 (必填 - 唯一标识符)",
    "login.emailPlaceholder": "电子邮箱 地址(选填 - 无需验证)",
    "login.registerBtn": "注册并登入",
    "login.alreadyHaveAccount": "已经有账号了？ ",
    "login.signInBtn": "登录",
    "login.loggingIn": "正在登录...",
    "login.creating": "正在创建账户并登入...",
    "login.errorNotFound": "凭证错误或找不到该用户。",
    "login.errorNotRegistered": "此电话号码未被注册。请点击下方“注册一个”进行账号注册。",
    "login.errorRequired": "姓名与手机号码均为必填项。",
    "login.errorAlreadyRegistered": "此电话号码已被注册。请尝试直接使用该号码登入。",
    "login.errorRegister": "注册时发生错误: ",

    // Route Search
    "search.routesBtn": "查询路线",
    "search.favsBtn": "我的收藏",
    "search.title": "您今天打算去哪里？",
    "search.desc": "一键寻找马那瓜出行的最佳公共交通路线",
    "search.originPlaceholder": "起点（例如：UCA，Naucalpan...）",
    "search.destPlaceholder": "终点（例如：Metrosur...）",
    "search.gpsBtn": "使用我的 GPS 定位",
    "search.gpsLocating": "定位中...",
    "search.submitBtn": "优化并生成路线",
    "search.loadingBtn": "正在寻找最佳出行方案...",
    "search.favTitle": "我收藏的路线",
    "search.favNone": "您尚未收藏任何路线。",
    "search.favDesc": "点击任意路线卡片上的红心，即可将其保存到此列表。",
    "search.suggested": "系统推荐路线",
    "search.bestChoice": "最佳推荐",
    "search.minutes": "分钟",
    "search.stops": "个经停站",
    "search.startBtn": "开始导航",
    "search.reportBtn": "投诉报告",
    "search.ready": "准备好开始旅程了吗？",
    "search.readyDesc": "在上方输入您的起点和目的地，即可探索马那瓜市内所有适用的路线方案。",

    // Navigation Tab
    "nav.titleReal": "实时 GPS 路径导航",
    "nav.titleStatic": "静态换乘指引",
    "nav.live": "实时",
    "nav.static": "静态",
    "nav.assignedDriver": "当前值班司机",
    "nav.staticStepPrefix": "途经地点",
    "nav.guideCenter": "乘车指南",
    "nav.guideCenterDesc": "请在下方查看每一站的信息和预估换乘，以便您顺利完成行程。",
    "nav.boardInstructions": "请在指定的公车站台等候并上车。",
    "nav.transferInstructions": "进行公交路线换乘。",
    "nav.nextOne": "下一个站台",
    "nav.arriveInstructions": "准备下车。您已到达终点站。",
    "nav.start": "起点",
    "nav.completed": "已完成",
    "nav.end": "终点",
    "nav.nextUnit": "线路上最近的车辆",
    "nav.arrivePrefix": "剩余时间:",
    "nav.arriveSuffix": "分钟",
    "nav.finish": "结束行程",
    "nav.howToTravel": "您想如何出行？",
    "nav.travelDesc": "选择您更喜欢的方式，在地图上动态或静态地展示您的旅程。",
    "nav.realTimeOption": "实时 GPS 模拟导航",
    "nav.realTimeDesc": "实时追踪车辆位置的模拟动画以及动态倒计时。",
    "nav.staticOption": "静态线路运行图",
    "nav.staticDesc": "直接在地图上完整呈现官方规定的推荐路线与经停站，无需运动模拟。",

    // Report Form
    "report.title": "上报异常事件",
    "report.subtitle": "保障您的平安出行是我们的首要使命",
    "report.successTitle": "报告发送成功！",
    "report.successDesc": "感谢您的宝贵建议。管理员将尽快核实并处理您上报的问题。",
    "report.question": "您想要投诉或举报什么？",
    "report.route": "公交车辆/路线",
    "report.driver": "当班司机",
    "report.both": "两者均上报",
    "report.reasonLabel": "请问具体原因是什么？",
    "report.reason_drunk": "司机疑似酒驾",
    "report.reason_reckless": "危险/超速驾驶",
    "report.reason_bad_condition": "车况极差/破损严重",
    "report.reason_other": "其他原因",
    "report.descLabel": "详细经过描述",
    "report.descPlaceholder": "请输入更详尽的客观事实或场景细节，以便我们核对...",
    "report.submitting": "正在发送中...",
    "report.sendBtn": "提交报告",

    // Admin Panel
    "admin.dashboard": "控制台主页",
    "admin.routes": "路线管理",
    "admin.stops": "经停公车站",
    "admin.drivers": "司机名册",
    "admin.reports": "投诉处理",
    "admin.schedules": "发车频率",
    "admin.manageSystem": "综合交通运输系统管理面板",
    "admin.addRoute": "添加路线",
    "admin.addStop": "添加站点",
    "admin.addDriver": "录用司机",
    "admin.addSchedule": "新增排班",
    "admin.routeCode": "车牌号 / 代号",
    "admin.routeName": "线路名称",
    "admin.stopName": "站点名",
    "admin.stopLat": "纬度 coordinates",
    "admin.stopLng": "经度 coordinates",
    "admin.driverName": "司机姓名",
    "admin.driverBio": "司机简历/描述",
    "admin.driverPhoto": "个人白底照片链接 URL",
    "admin.saveBtn": "保存更改",
    "admin.editBtn": "编辑",
    "admin.deleteBtn": "删除",
    "admin.configBtn": "偏好设置",
    "admin.recentReports": "最新事件排查",
    "admin.pending": "等候核实",
    "admin.resolved": "已处理妥当",
    "admin.allSaved": "更改已成功写入集群",
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations['es']) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('appLanguage');
    return (saved === 'en' || saved === 'zh' || saved === 'es') ? (saved as Language) : 'es';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('appLanguage', lang);
  };

  const t = (key: keyof typeof translations['es']): string => {
    const dict = translations[language] || translations['es'];
    return dict[key] || translations['es'][key] || String(key);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
